language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: SKIP_UNIT_TEST=y
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 8.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $SKIP_UNIT_TEST = 'y' ]]; then echo "Skipping composer update..."; fi
  - if [[ $SKIP_UNIT_TEST != 'y' ]]; then composer update --no-suggest --prefer-dist --no-interaction; fi

script:
  - if [[ $SKIP_UNIT_TEST = 'y' ]]; then echo "No unit test. done"; fi
  - if [[ $SKIP_UNIT_TEST != 'y' ]]; then ./vendor/bin/phpunit --whitelist src/ --coverage-clover=coverage.xml --debug; fi

after_success:
  - if [[ $SKIP_UNIT_TEST != 'y' ]]; then bash <(curl -s https://codecov.io/bash); fi
